### ISSUE TITLE
series2/usart/spi_master_dma- Need to set IGNORESREQ field to match with RM recommendation

### ISSUE THREAD

**Issue by silabs-Ruibin** [SiliconLabs/peripheral_examples#100]
**Example path, file name, line number(s)**
series2/USART/spi_master_dma/src/main_s2.c

**Gecko SDK Suite version**
Gecko SDK v3.2

**Board**
BRD4182A

**Expected behavior**
According to the RM section 21.3.9, when SPI is using Synchronous mode full duplex operation if both receive buffer and transmit buffer is served by DMA, to make sure receive buffer is not overflowed the settings below should be followed:
• The DMA channel that serves receive buffer should have higher priority than the DMA channel that serves transmit buffer.
• TXBL should be used as write request for transmit buffer DMA channel.
• IGNORESREQ should be set for both DMA channel. (This is not followed)

**Observed/problematic behavior**
• IGNORESREQ should be set for both DMA channel. (This is not followed)

**Comment by silabs-spurthi** [comment]
Thank you for catching this Ruibin! This enhancement is now implemented and pushed.
