### ISSUE TITLE
iadc calibration code bug 

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/peripheral_examples#101]
/series2/iadc/iadc_single_calibration

the code get scale wrongly after offset calibration.
it should also consider the msb gain.

`
  scale = IADC_SCALE_GAIN3MSB_GAIN100 | (IADC_CALIBRATED_GAIN13LSB << _IADC_SCALE_GAIN13LSB_SHIFT)
          | (IADC_CALIBRATED_OFFSET & _IADC_SCALE_OFFSET_MASK);

  IADCRescale(scale);

  // Infinite loop`

**Comment by silabs-marao** [comment]
@silabs-DenverL - which line is this in reference to? The same code is being used after offset correction to calculate scale. Please clarify if this is still an issue. Thanks!

**Comment by silabs-marao** [comment]
This has been fixed in 3bc29eca1e2dd0a53b25289e9c6bfcf9fecf17a5. Closing as resolved.
