### ISSUE TITLE
clock for EM01GRPACLK

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/peripheral_examples#107]
/series2/iadc/iadc_scan_iadc_timer/src/main_scan_iadc_timer.c

for EFR32MG22 (BRD4182A), this use **80MHz** for cmuClock_EM01GRPACLK.
seems this violate the [datasheet](https://www.silabs.com/documents/public/data-sheets/efr32mg22-datasheet.pdf), table 4.2 on page 19. the max for fEM01GRPBCLK is **76.8MHz**

**Comment by silabs-marao** [comment]
This issue is fixed in a6ae6d0980c478f44cf0928c2234c420d86b0b69. The clock source has been changed to HFXO from HFRCODPLL.
