### ISSUE TITLE
rising edge or falling edge

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/peripheral_examples#110]
series2/iadc/iadc_single_gpio_prs_ldma

readme me says:
 triggered by **falling** edge of GPIO via PRS.

code:
  initSingle.triggerSelect = iadcTriggerSelPrs0**PosEdge**;

**Comment by silabs-marao** [comment]
This issue has been fixed in 6873eb7d2377206baa7b139023e49f4052c0d8e7
