### ISSUE TITLE
reamme.md file

### ISSUE THREAD

**Issue by luweiguo511china** [SiliconLabs/peripheral_examples#112]
File https://github.com/SiliconLabs/peripheral_examples/blob/master/README.md

Remove one 'to'.
This repo, cloned to **to** C:\SiliconLabs\SimplicityStudio\v5\developer\repos\, where #.# is the Gecko SDK suite version number

**Comment by silabs-Ruibin** [comment]
This is addressed in commit 607c26d9ac4cbf9157f17394893459f40b5f6d7f
