### ISSUE TITLE
PWM PA6 mode setting for example EFR32 S2 timer_pwm_dma

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/peripheral_examples#120]
**Example path, file name, line number(s)**
(https://github.com/SiliconLabs/peripheral_examples/blob/master/series2/timer/timer_pwm_dma/src/main.c)

**Gecko SDK Suite version**
e.g. v4.2

**Board**
e.g. BRD4182A

**Expected behavior**
Should PA6 be set as pushpull mode?

**Observed/problematic behavior**
Set as input mode.
```
void initGPIO(void)
{
  // Configure PA6 as Input
  GPIO_PinModeSet(gpioPortA, 6, gpioModeInput, 0);
}

```
**Additional context**
Commit made the change
https://github.com/SiliconLabs/peripheral_examples/commit/4c12b259ecdae20667c91c5d6705a9c5b2299388
![image](https://user-images.githubusercontent.com/49192521/185039032-c3c633e0-bcb8-4700-ba6a-f0dbbb73f8a4.png)

**Comment by silabs-Joe** [comment]
Fixed in commit d990d89d29566c0fa9323351cc10190a168a9198
