### ISSUE TITLE
error when build the series 2 ldma_single_button project

### ISSUE THREAD

**Issue by luweiguo511** [SiliconLabs/peripheral_examples#14]
Below error showed up:
c:\siliconlabs\simplicitystudio\v4\developer\sdks\gecko_sdk_suite\v2.5\hardware\kit\common\bsp\bsp.h:25:10: fatal error: bspconfig.h: No such file or directory
 #include "bspconfig.h"
          ^~~~~~~~~~~~~
compilation terminated.
make: *** [src/main.o] Error 1
make: *** Waiting for unfinished jobs....

It looks need to manually include
"C:\SiliconLabs\SimplicityStudio\v4\developer\sdks\gecko_sdk_suite\v2.5\hardware\kit\EFR32MG21_BRD4181A\config"
or need to add below lines in studio file
C:\SiliconLabs\SimplicityStudio\v4\developer\sdks\gecko_sdk_suite\v2.5\.studio\modules\AllBoardsModule.slsproj
  
  <includePath uri="$(sdkInstallationPath:default())/hardware/kit/EFR32MG21_BRD4181A/config" boardCompatibility="brd4181a" />

**Comment by silabs-austin** [comment]
This problem has been resolved internally and will push out to the public with the next release of the 32-bit SDK. Manually including the kit configuration path in the project settings is a good work-around until the SDK update.
