### ISSUE TITLE
Seems the i2c example missed an project for EFM32TG/STK3300

### ISSUE THREAD

**Issue by luweiguo511** [SiliconLabs/peripheral_examples#18]
Code in folder series0/i2c/i2c/SimplicityStudio

**Comment by silabs-dayoung** [comment]
The example does not exist due to the EFM32TG-STK3300 not having a usable I2C pin. The readmes have been updated to explain the missing project.

**Comment by luweiguo511** [comment]
Thanks Manasa. That make sense to me.
