### ISSUE TITLE
I2S example doc

### ISSUE THREAD

**Issue by bmcdonnell-ionx** [SiliconLabs/peripheral_examples#2]
From https://github.com/SiliconLabs/peripheral_examples/blob/public/i2s/i2s/src/main_gg11.c:

```
/**************************************************************************//**
 * @file main_gg11.c
 * @brief This project demonstrates both master and slave configurations of the
 * EFM32 I2C peripheral. Two EFM32 I2C modules are connected and set up
 * to both transmit (master mode) and receive (slave mode) between each
 * other using a common I2C bus.
 * @version 0.0.1
 ******************************************************************************
```

Questions:

1. Is I2C a typo that should be I2S? i.e. "Two EFM32 *I2S* modules ... common *I2S* bus."
2. What does this mean? Where does the data come from? What is the hardware setup to run this project? One chip with a loopback? Or two micros?

**Comment by silabs-stephen** [comment]
The brief description in this file is incorrect. The readme in the parent directory is correct. This will be fixed in the next release.
