### ISSUE TITLE
Typo in file master/series1/i2c/i2c/src/main_tg11.c

### ISSUE THREAD

**Issue by luweiguo511** [SiliconLabs/peripheral_examples#21]
// Configure LED0 and LED1 as output
  GPIO_PinModeSet(BSP_GPIO_LED0_PORT, BSP_GPIO_LED0_PIN, gpioModePushPull, 0);
  GPIO_PinModeSet(BSP_GPIO_LED1_PORT, BSP_GPIO_LED1_PORT, gpioModePushPull, 0);
--->
  // Configure LED0 and LED1 as output
  GPIO_PinModeSet(BSP_GPIO_LED0_PORT, BSP_GPIO_LED0_PIN, gpioModePushPull, 0);
  GPIO_PinModeSet(BSP_GPIO_LED1_PORT, BSP_GPIO_LED1_PIN, gpioModePushPull, 0);

**Comment by silabs-marao** [comment]
This has now been fixed.

**Comment by luweiguo511** [comment]
Thanks.
