### ISSUE TITLE
spi_slave sends back garbage on first transfer

### ISSUE THREAD

**Issue by hajot** [SiliconLabs/peripheral_examples#23]
When running the spi_master and spi_slave code on EFM32GG11 eval boards, the second byte of the first transfer is always garbage.

I posted more details in the silabs forum:
https://www.silabs.com/community/mcu/32-bit/forum.topic.html/efm32_gg11_interruptdrivenspiexamplefromgi-2Iz5

**Comment by silabs-BrianL** [comment]
resolved in https://github.com/SiliconLabs/peripheral_examples/commit/734df733775d8272f253077b742d7384a9e94eec
