### ISSUE TITLE
USBD examples do not build

### ISSUE THREAD

**Issue by aspdigital** [SiliconLabs/peripheral_examples#26]
The USBD examples do not build, at least on EFM32GG11.
The tools can't find the file em_usb.h.

The include paths setting has 
`
C:/Users/andy/Projects/peripheral_examples.git/platform/middleware/usb_gecko/inc`

instead of ${StudioSdkPath}/platform/middleware/usb_gecko/inc

I also get this error:
`
make: *** No rule to make target C:/Users/andy/Projects/peripheral_examples.git/platform/middleware/usb_gecko/src/em_usbd.c', needed by emusb/em_usbd.o'.  Stop.`

I'm not sure how to fix this second issue.

**Comment by silabs-marao** [comment]
These issues have been fixed in commit 90c8e8757fba5ce06866889e53d10f1904004d3b.
