### ISSUE TITLE
ADC examples' samplerates massively off

### ISSUE THREAD

**Issue by tgipsonMIDE** [SiliconLabs/peripheral_examples#27]
Hi,
It looks like the ADC examples (at least adc_scan_letimer_prs_dma) have a bug where the user-configured samplerate is ignored and a very low (a few Hz) samplerate is used instead. Using src/main_gg11_xg14.c as an example, the beginning of the file has the following definitions:

> #define letimerClkFreq  19000000
// Desired letimer interrupt frequency (in Hz)
#define letimerDesired  1000

However, the 19MHz "letimerClkFreq" value is nonsense (the LETIMER can only be clocked by LFXO, LFRCO, or ULFRCO according to the reference manual) and will result in a samplerate that is massively off since the real LETIMER frequency is ~32KHz. 

Suggest computing the LETIMER compare at runtime based on the actual LETIMER frequency, e.g.:

>   letimer_freq = CMU_ClockFreqGet(cmuClock_LETIMER0);
  letimer_compare = letimer_freq / (letimerDesired+1); // less surprising results when choosing an exact-match samplerate (e.g. 32768/n) for letimerDesired
  // Compare on wake-up interval count
  LETIMER_CompareSet(LETIMER0, 0, letimer_compare);

Thanks!

**Comment by silabs-BrianL** [comment]
Resolved in commit 734df733775d8272f253077b742d7384a9e94eec
