### ISSUE TITLE
ADC Examples for Series 2?

### ISSUE THREAD

**Issue by SimonMorrison** [SiliconLabs/peripheral_examples#29]
Does any of the series 2 examples contain a simple one for the ADC?

Thanks in advance. Simon

**Comment by silabs-BrianL** [comment]
Currently, there are only series 2 IADC examples in the AN1189 appnote:
https://www.silabs.com/documents/public/application-notes/an1189-efr32-iadc.pdf
https://www.silabs.com/documents/public/example-code/an1189-efm32-iadc.zip
