### ISSUE TITLE
Windows 7 USB CDC Support

### ISSUE THREAD

**Issue by rdb9879** [SiliconLabs/peripheral_examples#3]
Just a note on getting the USB CDC examples to work on Windows 7 on the Giant Gecko Series 1: I used this Pololu CDC driver: https://github.com/pololu/p-star-examples/blob/master/drivers/p-star-serial.inf

and managed to get the examples working on Windows 7. Steps: download the inf file, right click -> Install, then in the device driver -> Update Driver..., Follow the steps to manually select from installed drivers, and it should appear as Pololu P-Star. 

After this, the device appeared as a COM port, and worked as expected.
[p-star-serial.zip](https://github.com/SiliconLabs/peripheral_examples/files/2659873/p-star-serial.zip)

**Comment by silabs-MitchC** [comment]
Hi @rdb9879 ,

Thank you for this information.  We are glad to see that our USB CDC examples are useful, and appreciate your suggestions to the community that can aid in development.  

Regards,
Mitch
