### ISSUE TITLE
Device part number typo for BRD4161A

### ISSUE THREAD

**Issue by luweiguo511** [SiliconLabs/peripheral_examples#32]
readme.txt file for /series1/timer/timer_pulse_capture:

Board:  Silicon Labs EFR32MG12P Starter Kit (BRD4161A)
Device: EFR32MG1P432F1024GL125
PC10 - TIM0_CC0 #15 (Expansion Header Pin 15)

Device should be corrected as EFR32MG12P432F1024GL125

**Comment by silabs-spurthi** [comment]
Fixed in 6e45f97525eba6ffd8aa6d06a3b81414c44bdd3a commit
