### ISSUE TITLE
ADC Scan mode example 

### ISSUE THREAD

**Issue by luweiguo511** [SiliconLabs/peripheral_examples#33]
For /master/series1/adc/adc_scan_interrupt/src
the code use AVDD as input channel.
  // Select ADC input. See README for corresponding EXP header pin.
  // Add VDD to scan for demonstration purposes
  ADC_ScanSingleEndedInputAdd(&initScan, adcScanInputGroup0, adcPosSelAPORT2XCH9);
  ADC_ScanSingleEndedInputAdd(&initScan, adcScanInputGroup1, adcPosSelAVDD);

Reference manual has below words (take EFM32GG11 as example, section 27.3.5.2 on page 1024).
In scan mode, the ADC can sample and convert up to 32 external channels on each conversion trigger. Internal channels are not available in scan mode.
What done the words/comment meant to say in the source code:
"Add VDD to scan for demonstration purposes"

You should put some words in the source or readme file to make this more clear.

**Comment by silabs-austin** [comment]
Fixed in commit [67fc793c854e41e9b757b7ed26715fede3c21df3](https://github.com/SiliconLabs/peripheral_examples/commit/67fc793c854e41e9b757b7ed26715fede3c21df3)
