### ISSUE TITLE
part for radio board BRD4161A

### ISSUE THREAD

**Issue by luweiguo511** [SiliconLabs/peripheral_examples#34]
the part in file /series1/usart/async_polled/SimplicityStudio/BRD4161A_EFR32MG12P_async_polled.slsproj
should be efr32mg12p432f1024gl125, not *efr32mg12p433f1024gl125.

**Comment by silabs-spurthi** [comment]
Fixed in 6e45f97525eba6ffd8aa6d06a3b81414c44bdd3a commit
