### ISSUE TITLE
comment improvement for 

### ISSUE THREAD

**Issue by luweiguo511** [SiliconLabs/peripheral_examples#37]
File https://github.com/SiliconLabs/peripheral_examples/blob/master/series1/gpio/switch_led_polled/src/main_gg11.c

`  // Configure GPIO pins

  CMU_ClockEnable(cmuClock_GPIO, true);`

---->
`  // Enable clock

  CMU_ClockEnable(cmuClock_GPIO, true);`

**Comment by silabs-spurthi** [comment]
Fixed in 6e45f97525eba6ffd8aa6d06a3b81414c44bdd3a commit
