### ISSUE TITLE
ADC/LETIMER/PRS/LDMA DVL not used

### ISSUE THREAD

**Issue by burindes** [SiliconLabs/peripheral_examples#4]
Hi,
In the ADC single LETIMER / PRS / DMA example, the ADC_DVL value is not used in the code: 
https://github.com/SiliconLabs/peripheral_examples/blob/2e335349734c96f3f53fdd6d4dc879da2a44222e/adc/adc_single_letimer_prs_dma/src/main_s1.c#L33

I suppose the SINGLECTRLX register should be altered, and in some way the LDMA should be told to fetch values ADC_DVL by ADC_DVL (2 by 2 in our example)?

Regards

**Comment by silabs-MitchC** [comment]
Hi @burindes ,

Thank you for bringing this to our attention.  We have addressed this issue in the ADC single LETIMER / PRS / DMA example and it will be fixed in the next release.

Regards,
Mitch
