### ISSUE TITLE
SADDR is set but SADDRMASK is not set

### ISSUE THREAD

**Issue by JonathanNorton** [SiliconLabs/peripheral_examples#44]
https://github.com/SiliconLabs/peripheral_examples/blob/b7a74db03edbcc125dad23a964d615039a86b7ac/series1/i2c/i2c/src/main_tg11.c#L124

**Comment by JonathanNorton** [comment]
This applies to other examples too.

**Comment by luweiguo511** [comment]
I agree, looks EFR32 S2 are ok.

**Comment by silabs-austin** [comment]
Fixed in https://github.com/SiliconLabs/peripheral_examples/commit/ff9b8bd41177e9c912ac6544d446bf463081663c
