### ISSUE TITLE
Improper flag usage

### ISSUE THREAD

**Issue by silabs-EricB** [SiliconLabs/peripheral_examples#45]
https://github.com/SiliconLabs/peripheral_examples/blob/49e1c526edb2e35ad544bca7d0a0ecbb5872f67d/series2/iadc/iadc_scan_interrupt/src/main_scan_interrupt.c#L182
https://github.com/SiliconLabs/peripheral_examples/blob/67fc793c854e41e9b757b7ed26715fede3c21df3/series2/iadc/iadc_scan_timer/src/main_scan_timer.c#L161

I think the flag **_IADC_IF_SCANTABLEDONE_** should be used instead for clearing the interrupt.

**Comment by silabs-DenverL** [comment]
To make the code more readable, I agree with you.
In fact there are many many places in the examples that don't differentiate IEN/IF/IFC.
The good thing is that the position of these bit-field are same in register IEN, IF and IFC, etc.

**Comment by silabs-dayoung** [comment]
Fixed in d502ada
