### ISSUE TITLE
Remove driver folder

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/peripheral_examples#52]
the example don't use retargetio.c retargetserial.c
https://github.com/SiliconLabs/peripheral_examples/tree/master/series2/gpio/gpio_int/SimplicityStudio
![image](https://user-images.githubusercontent.com/49192521/91697775-413e7e80-eba4-11ea-9276-4e0aff771acf.png)

**Comment by silabs-DavidS** [comment]
Thank you for your feedback Denver. I have removed the unneeded includes from this project.
