### ISSUE TITLE
GPIO_IntConfig or GPIO_ExtIntConfig

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/peripheral_examples#54]
Example gpio_int for S2 still use obsoleted GPIO_IntConfig API. 
https://github.com/SiliconLabs/peripheral_examples/tree/master/series2/gpio/gpio_int

`  /* Configure Button PB0 as input and enable interrupt */
  GPIO_PinModeSet(BSP_GPIO_PB0_PORT, BSP_GPIO_PB0_PIN, gpioModeInputPull, 1);
  GPIO_IntConfig(BSP_GPIO_PB0_PORT, BSP_GPIO_PB0_PIN, false, true, true);

  /* Configure Button PB1 as input and enable interrupt */
  GPIO_PinModeSet(BSP_GPIO_PB1_PORT, BSP_GPIO_PB1_PIN, gpioModeInputPull, 1);
  GPIO_IntConfig (BSP_GPIO_PB1_PORT, BSP_GPIO_PB1_PIN, false, true, true);`

**Comment by silabs-DavidS** [comment]
Hi Denver,

This method, while deprecated, has been refactored to simply call GPIO_ExtIntConfig, and is unlikely to be removed from the SDK. That being said I agree that using GPIO_ExtIntConfig is a better practice, and have updated the series 2 GPIO examples accordingly.

An associated commit will be submitted shortly.

Best,
David
