### ISSUE TITLE
change for SLWRB4181A to SLWRB4181B 

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/peripheral_examples#55]
[according PCN 200915847 ](https://www.silabs.com/documents/public/pcns/200915847-SLWSTK6006A-and-SLWSTK6023A-kits-updated-with-new-boards-SLWRB4180B-and-SLWRB4181B.pdf). there are hardware change on the radio board.
Should we make necessary change on our examples to match the hardware change (like GPIO swap for LESs and buttons).
/master/series2/gpio/gpio_int

**Comment by silabs-DavidS** [comment]
Thank you for the feedback Denver. This change would potentially affect a large number of example projects; any series 2 examples using the BSP headers, of which there are many.

Generally in this repository the project support exists for one kit per MCU. Support for other kits is provided through the use of the BSP headers, which allows for quick porting to other kits.

As a result, I'm thinking that going forward we create new projects targeting BRD4181B, but keep existing project files as is. Additionally I will add documentation to the readme explaining how to port examples to other kits. We have this information on other applications_examples repositories, and it will be good to add it here as well.

An associated commit will be submitted shortly.

Thanks again,
David
