### ISSUE TITLE
single ended or differential mode for 16bit ADC example

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/peripheral_examples#57]
I suggest change the code to differential mode:
iadc/iadc_single_16bit/src/main_single_16bit_xG22.c.
the ENOB characterization data in the datasheet was got with differential mode.

**Comment by silabs-dayoung** [comment]
On the xG22 devices, single-ended mode technically functions as differential mode with the negative pin internally tied to ground. So the ENOB characterization data should also apply to single-ended mode. Because of this, the suggested change will not be implemented.
