### ISSUE TITLE
i2cClockHLRStandard or i2cClockHLRAsymetric

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/peripheral_examples#59]
https://github.com/SiliconLabs/peripheral_examples/tree/master/series1/i2c/i2c

since we are set the speed as fast, I suggest we use 6:3 asymmetry ratio, otherwise we may violate the I2C tlow spec for fast mode.
Though the real speed may lower than 400k.

**Comment by silabs-dayoung** [comment]
You are right. The real speed is lower than 400k, but it is safer to use the 6:3 clock ratio in case a change is made to use a different clock source. A fix for this is implemented in commit c8bcb077c4e7127b7f810b0f78f64b7d8541761f
