### ISSUE TITLE
three source file for iadc example

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/peripheral_examples#60]
any reason there are 3 source files for 
peripheral_examples/series2/iadc/iadc_single_em2/src/
![image](https://user-images.githubusercontent.com/49192521/96970017-a2038b00-1545-11eb-940e-011c09cc976e.png)

**Comment by silabs-dayoung** [comment]
The main_single_em2.c file should not exist. It has been removed in commit 27061bd0ff7315db7466c18f2f80b96eac88654c
