### ISSUE TITLE
i2c example cleanup

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/peripheral_examples#62]
/series1/i2c/i2c/src/main_efr.c
it looks the macro like below was not used in the code.
`#define CORE_FREQUENCY              14000000`
`#define RTC_MIN_TIMEOUT                32000`
I don't see there is necessary to enable HFLE clock.
`CMU_ClockEnable(cmuClock_HFLE, true);`

**Comment by silabs-dayoung** [comment]
Yes, those macros are not needed in the series 1 I2C project. This has been removed in commit c9d6dc8812b9f89573986765241ed64252a6b496
