### ISSUE TITLE
timer FRG example

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/peripheral_examples#63]
https://github.com/SiliconLabs/peripheral_examples/blob/master/series2/timer/timer_frequency_generation/src/main.c
The RM does not document this well.
The FRG utilize the cofoa/cufoa/cmoa to toggle the output/pin to generate a specific frequency.

Beside the method mentioned in the RM, below should also ok to generate frequency signal:
a. down-count mode, and enable cufoa activation.
b. up-count or down-count, enable cmoa activation. but the CCx value should lower than TOP value. 
Currently the example use up-count and cmoa activation.

to keep consistent with the RM, suggest to change cmoa to cofoa.
`  timerCCInit.mode = timerCCModeCompare;
`

--->
`  timerCCInit.cufoa = timerOutputActionToggle;
`

**Comment by silabs-austin** [comment]
Fixed in commit https://github.com/SiliconLabs/peripheral_examples/commit/00621046b6e0bb7488ce4131d098b7fccfed82a1
