### ISSUE TITLE
EFM32GG11 I2C example typo.

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/peripheral_examples#64]
https://github.com/SiliconLabs/peripheral_examples/blob/master/series1/i2c/i2c/src/main_gg11.c
It use PC0 and PC1 (instead of PC10 and PC11).
  // Using PC10 (SDA) and PC11 (SCL)
  GPIO_PinModeSet(gpioPortC, 0, gpioModeWiredAndPullUpFilter, 1);
  GPIO_PinModeSet(gpioPortC, 1, gpioModeWiredAndPullUpFilter, 1);

**Comment by silabs-austin** [comment]
Fixed in commit https://github.com/SiliconLabs/peripheral_examples/commit/0b4b798fb5dce982d92a9b9bd7c10cc6cf07e35e
