### ISSUE TITLE
Timer PWM DMA example for EFR32 S2

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/peripheral_examples#65]
https://github.com/SiliconLabs/peripheral_examples/blob/master/series2/timer/timer_pwm_dma/src/main.c
I suggest to not use 100 duty cycle to avoid glitch.

// Buffer size
#define BUFFER_SIZE 11
// Note: change this to change the duty cycles used in this example
static const uint16_t dutyCyclePercentages[BUFFER_SIZE] =
    {0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100};

-->
// Buffer size
#define BUFFER_SIZE 10
// Note: change this to change the duty cycles used in this example
static const uint16_t dutyCyclePercentages[BUFFER_SIZE] =
    {0, 10, 20, 30, 40, 50, 60, 70, 80, 90};

**Comment by silabs-austin** [comment]
Fixed with commit https://github.com/SiliconLabs/peripheral_examples/commit/17c8e57d5aeae41adc46b9981fb19f888278916e
