### ISSUE TITLE
minimum period pulse timer capture.

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/peripheral_examples#66]
series0/timer/timer_pulse_capture/
Note: The range of frequencies this program can measure accurately is limited.
The minimum measurable period is around **700** ns, or **1.43** MHz.

I guess this limitation come from interrupt latency.

Suggest add: 
refer to AN0039.

**Comment by silabs-austin** [comment]
Addressed with commit https://github.com/SiliconLabs/peripheral_examples/commit/3b9f4bb09fcaa7756a7ae16a70600f363a03626b
