### ISSUE TITLE
I2C slave example for S2

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/peripheral_examples#69]
peripheral_examples/series2/i2c/i2c_slave/src/main.c

In void initI2C(void)
This line maybe is not needed.
I2C0->CTRL = I2C_CTRL_SLAVE;

I think the I2C_Init will write the bit-field already.
  /* Set SLAVE select mode. */
  BUS_RegBitWrite(&(i2c->CTRL), _I2C_CTRL_SLAVE_SHIFT, init->master ? 0 : 1);

**Comment by silabs-austin** [comment]
Fixed with commit https://github.com/SiliconLabs/peripheral_examples/commit/677b1d1c01b15b736eabf5aa553de43f0f81add2
