### ISSUE TITLE
USART examples miss-use USART_IF_RXDATAV to clear interrupt flags

### ISSUE THREAD

**Issue by silabs-AntonioT** [SiliconLabs/peripheral_examples#73]
Applicable examples are:

- spi_master
- spi_slave
- async_interrupt
- usart_async_interrupt
- usart_spi_slave_interrupt

RXDATAV is cleared by hardware when the RX buffer is cleared. A software approach with USART_IntClear leads to writing a reserved bifield.

**Comment by silabs-DenverL** [comment]
![image](https://user-images.githubusercontent.com/49192521/105963569-1bb69200-60bc-11eb-97ca-db5c06ef6b7b.png)
`  USART_IntClear(USART0, USART_IF_RXDATAV);`
