### ISSUE TITLE
Series 2 I2C slave example not functioning properly due to race condition

### ISSUE THREAD

**Issue by silabs-dayoung** [SiliconLabs/peripheral_examples#74]
There's a race condition in the I2C slave example where an I2C interrupt can occur in the middle of the em_EM2_RTCC function before the device actually enters EM2. This I2C interrupt is a response to the master sending a START+ADDR+R/W frame, trying to initiate another I2C transfer. At this point, the slave device should not enter EM2, but as soon as it exits the I2C handler, it goes into EM2 without doing another check of the i2c_rxInProgress variable.

Proposed solution is to define the em_EM2_RTCC function as a critical section by using the CORE_ENTER_CRITICAL() and CORE_EXIT_CRITICAL() functions thereby preventing an I2C interrupt to ACK the master's transmission.

**Comment by silabs-Ruibin** [comment]
Thanks for catching this issue. This issue is addressed and pushed.
