### ISSUE TITLE
minor typo in readme, series0/dac/dac_voltage

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/peripheral_examples#75]
readme.txt
Board: Silicon Labs EFM32G Starter Kit (STKXXX)
Device: EFM32GG890F128
PB11 - DAC0_OUT0
-->
Board: Silicon Labs EFM32G Starter Kit (STKXXX)
EFM32G890F128
PB11 - DAC0_OUT0

**Comment by silabs-DavidS** [comment]
Thanks for reporting the issue, this has been addressed in c8b6083ed10
