### ISSUE TITLE
Series1 USART spi master example - Rx buffer bytes shifted by 1

### ISSUE THREAD

**Issue by silabs-marao** [SiliconLabs/peripheral_examples#81]
**Examples that show this issue**: spi_master on PG1; spi_master on xg12

**Description**: Per the instructions in the readme, the rx buffer in the spi_master code should contain 0xA0, 0xA1,...0xA9. However, it looks like the RX buffer contains 0xA1, 0xA2, ... , 0xA9, 0xA0. 

This needs to be investigated. This might also be applicable to other Series1 examples not impacted by #73

**Comment by silabs-JohnB** [comment]
Fixed in [80a3a57](https://github.com/SiliconLabs/peripheral_examples/commit/80a3a57236047aaaace323c661f32dd556527e07).

**Comment by silabs-JohnB** [comment]
Fixed in 80a3a57236047aaaace323c661f32dd556527e07.

**Comment by silabs-JohnB** [comment]
Fixed in 80a3a57236047aaaace323c661f32dd556527e07.
