### ISSUE TITLE
Series 2 SPI master/slave RX buffer shifted by varying amounts

### ISSUE THREAD

**Issue by silabs-Joe** [SiliconLabs/peripheral_examples#82]
The description of the spi master example states that the input buffer should match the output buffer (0..9).  After running the project for a while (it loops, rather than sending 10 bytes then stopping), the input buffer can become out of sync, for example 9,0,1,2,3,4,5,6,7,8.  

This was tested with EFR32xG22 running the spi_master demo and EFR32xG21 running the spi_slave demo.

**Comment by silabs-JohnB** [comment]
Fixed in 80a3a57236047aaaace323c661f32dd556527e07.
