### ISSUE TITLE
prescale for VDAC EFM32 S0

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/peripheral_examples#84]
series0/vdac/vdac_sine_wave_synch
Should be **8**, not **128**.

The PRESCALE bitfield is different for series 0 and series 1 boards. For series
0 boards, the bitfield is 3 bits so the actual prescaler can be any power of 2
between 1 and **128**. For series 1 boards, the bitfield is 7 bits so the actual
prescaler can be any number between 1 and 128. The prescaler must be chosen, as
mentioned above, to ensure that the DAC_CLK is less than or equal to 1 MHz.

**Comment by silabs-JohnB** [comment]
This appears to be correctly coded and documented in both the S0 and S1 vdac_sine_wave_synch examples. In the case of the S0 example, PRESCALE = 4, which would make the DAC_CLK = HFPERCLK / 2^PRESCALE = 14 MHz / 16 = 0.875 MHz, which complies with the <= 1 MHz requirement.

The readme.txt says "For series 0 boards, the bitfield is 3 bits so the actual prescaler can be any power of 2 between 1 and 128," which is essentially correct. There might be a clearer way to state this, but the example code shows how the sine wave frequency is calculated and does explain that PRESCALE <= 7.
