### ISSUE TITLE
cdc_echo.c or cdc.c

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/peripheral_examples#85]
series0/usbd/usbd_cdc_vcom_echo
Seems like should be cdc_ecko.c

Note: The callback functions in **src/cdc.c** are named with respect to the USB
device (in this case the EFM32 board). For example, usbDataTransmitted() gets
called when the USB device transmits data over USB to the host.

**Comment by silabs-dayoung** [comment]
All instances of cdc.c in the comments were replaced with cdc_echo.c in commit 7a178d6da40332a4fffa8fcc53b8a272c4f118e2.
