### ISSUE TITLE
cdc.h header file

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/peripheral_examples#86]
series0/usbd/usbd_cdc_uart_bridge/inc/

a. indent for usbconfig.h ( inc_series0/)
b. we may don't need cdc.h in /series0/usbd/usbd_cdc_uart_bridge/inc, the code looks like use cdc.h in C:\SiliconLabs\SimplicityStudio\v4\developer\sdks\gecko_sdk_suite\v2.7\hardware\kit\common\drivers

  - inc

      inc_hg/
        usbconfig.h

      inc_series0/
        usbconfig.h

**Comment by silabs-dayoung** [comment]
The project is indeed using the SDK's cdc.h file, so the file has been removed from the project directory.
The project directly structure in the readme has been updated to include the indentation and removes the cdc.h file.
These changes have been implemented in commit 7a178d6da40332a4fffa8fcc53b8a272c4f118e2.
