### ISSUE TITLE
gpio interrupt

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/peripheral_examples#87]
series0/pcnt/pcnt_extclk_single_overflow/src/main_g.c

to keep consistence, could we remove the GPIO interrupt ISR code.

void GPIO_ODD_IRQHandler(void)
{
  /* Acknowledge all odd number pin interrupt */
  GPIO_IntClear(0xAAAA);

  /* Toggle PC5 */
  GPIO_PinOutToggle(gpioPortC, 5);
}

**Comment by silabs-dayoung** [comment]
The other pcnt_extclk_single_overflow examples use the PRS to connect the GPIO input to the PCNT. On EFM32G, the PCNT is not an eligible PRS consumer, so GPIO interrupts are used instead to notify the PCNT of an input pulse.
