### ISSUE TITLE
current consumption on EFM32 S0

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/peripheral_examples#88]
Take the series0/vdac/vdac_timer_dma_waveform as example, 
We give the current measured on EFM32GG11, is it possible we measure the current on EFM32 S0 and update the readme file?

This example used about 1.37 milliamps on average. After commenting out the line
of code that puts the board in EM1, this example used about 2.07 milliamps on
average. Note: this energy measurement was done using Simplicity Studio's
built-in energy profiler for a **GG11** board with a Debug build configuration and no
optimization flags (gcc -O0).

**Comment by silabs-stephen** [comment]
Hi Denver, thank you for the suggestion. We will consider this in the future. Best regards.
