### ISSUE TITLE
PDM example clock select bug

### ISSUE THREAD

**Issue by silabs-zee** [SiliconLabs/peripheral_examples#89]
**CMU_ClockSelectSet(cmuClock_PDM, cmuSelect_HFRCODPLL)** at [line 79 of main_pdm_stereo_ldma.c ](https://github.com/SiliconLabs/peripheral_examples/blob/master/series2/pdm/pdm_stereo_ldma/src/main_pdm_stereo_ldma.c#L79) and at [line 66 of main_pdm_stereo_interrupt.c](https://github.com/SiliconLabs/peripheral_examples/blob/master/series2/pdm/pdm_stereo_interrupt/src/main_pdm_stereo_interrupt.c#L66) should be **CMU_ClockSelectSet(cmuClock_PDMREF, cmuSelect_HFRCODPLL)**. cmuClock_PDM is not referenced in any case in the switch statement in CMU_ClockSelectSet this will cause assertion in em_cmu.c. This bug is probably slipped through as assertion is not enabled by default till SDK 3.1.

**Comment by silabs-DenverL** [comment]
It is strange why the example don't call API like PDM_Init provided in emlib file em_pdm.c/h. instead we write and read the PDM register directly.
I remove the em_pdm.c and em_pdm.h the project still pass build

**Comment by silabs-zee** [comment]
nonetheless, even without adding those, this example still would not work with assertion enabled. That line calling CMU_CloclSelectSet is just plain wrong.

**Comment by silabs-zee** [comment]
There is no ** cmuClock_PDM** instead of CMU_ClockSelectSet switch statement, you will see assertion triggered if you enable debug assertion.

**Comment by silabs-DenverL** [comment]
> There is no **cmuClock_PDM** instead of CMU_ClockSelectSet switch statement, you will see assertion triggered if you enable debug assertion.

Yes, I agree with you.
My personal understanding is that the example is supposed to call emlib driver, in fact almost all of other examples already call emlib driver. I would suggest we also made necessary change to call API provided in em_pdm.c/h.

**Comment by silabs-zee** [comment]
That would be one stone two birds XD

**Comment by silabs-austin** [comment]
Fixed with commit https://github.com/SiliconLabs/peripheral_examples/commit/9116444ed5ae8b3cda3475b1d03a8589f2a8312f
